version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432" 
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  pg_data:
